version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: redluc/docker-learning:compose
    ports:
      - "8091:8090"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:








